import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WinnerIndicatorBanner } from "@/components/winner-indicator-banner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <WinnerIndicatorBanner />
        <div className="flex flex-col mx-auto items-center justify-center h-screen w-md gap-6 max-[448px]:px-4 max-[448px]:w-screen">
          {children}
        </div>
      </body>
    </html>
  );
}
